### PR TITLE
Fixes rootElement to match that of this.$()[0]

### LINKED ISSUE #63: Different rootElement than in jQuery based tests
Not sure if this is an issue or designed like that by intention, but at least it leads to some CSS selectors not working the same as in jQuery-based tests. 

When rendering a component in integration tests, the resulting DOM will look like this:

```html
<div id="ember-testing" class="ember-application">
  <div id="ember139" class="ember-view">
    <div id="ember187" class="my-component"></div>
  </div>
</div>
```

For `find` the `rootElement` is explicitly set to `#ember-testing`, while for `this.$()` the equivalent is the `#ember139` view. This results in the following incompatible difference when using the `:first-child` selector:

`find(':first-child')` -> `#ember139` (the wrapping view)
`this.$(':first-child')` -> `#ember187` (the actual component under test)

So when migrating, one would have to rewrite all those selectors. I would assume that it should actually behave the same, at least that would make migrating more straightforward. (I actually used this selector in ember-bootstrap quite often)

Would you consider this a bug? If not it should probably be documented. Also relates to #51, could make an automatic migration if this is not considered a bug and will stay like this...

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #63

See https://github.com/emberjs/ember-test-helpers/blob/1e505a9de65b6a6352abc16698df7e3eb816c151/addon-test-support/%40ember/test-helpers/setup-rendering-context.js#L152

Hopefully this will not affect too many users, but might still be a breaking change for some, so probably would require a minor version bump?

### CODE REVIEW

**Comment by pixelhandler** [comment]
@simonihmig nice, thanks for the fix to the root element. I'm curious, what do you think about adding a test for `find()` that asserts the returned element is identical to `document.querySelector('#ember-testing > .ember-view')` ?

- See https://github.com/cibernox/ember-native-dom-helpers/blob/master/tests/integration/find-test.js

**Comment by simonihmig** [comment]
@pixelhandler Sure, makes sense!

I added a test for `:first-child`. To make it pass I actually had to remove [this](https://github.com/cibernox/ember-native-dom-helpers/pull/121/files#diff-8f60a6be7648f7eda8ce189a29741c5e) from `test-helper.js`, because tests were effectively still running with `#ember-testing` (taken from dummy config) as their rootElement. Not sure though why this was in place, so please double check! :)

Regarding `find()`: not sure what the semantics should be. Currently this will result in a `'#ember-testing > .ember-view undefined'` query, so returns `null`. Should it instead return the root element? 

For comparison, with legacy Ember tests `find()` (the jquery-based global acceptance test helper) returns `undefined`, but `this.$()[0]` (integration test) will indeed return the root element.

File: addon-test-support/settings.js [hunk 1]
```diff
@@ -5,7 +5,7 @@
 */
 class TestSupportSettings {
 
-  constructor(init = { rootElement: '#ember-testing' }) {
+  constructor(init = { rootElement: '#ember-testing > .ember-view' }) {
```
Comment (rwjblue) [inline addon-test-support/settings.js]: I think we should expose this from `ember-test-helpers`.  I don't _really_ like encoding this in various places, as it has changed over time and might change again in the future.  

I'm thinking something like:

```js
import { rootElementSelector as rootElement } from 'ember-test-helpers';

class TestSupportSettings {
  constructor(init = { rootElement }) {

  }
}
```

What do y'all think?

Comment (simonihmig) [reply addon-test-support/settings.js]: 💯 agree!

See also https://github.com/simplabs/qunit-dom/issues/39 /cc @Turbo87

File: tests/test-helper.js [hunk 2]
```diff
@@ -3,10 +3,6 @@ import {
   setResolver
 } from 'ember-qunit';
 import { start } from 'ember-cli-qunit';
-import { settings } from 'ember-native-dom-helpers';
-import config from '../config/environment';
```
Comment (pixelhandler) [inline tests/test-helper.js]: @simonihmig I think we want to keep this, the thing about the root element is that it can be configurable, originally we set up like so: https://github.com/cibernox/ember-native-dom-helpers/blob/master/tests/dummy/config/environment.js#L43

So can just change the line in the dummy app config to agree with the other change `rootElement: '#ember-testing > .ember-view'`

File: addon-test-support/settings.js (hunk 1 above)
Comment (pixelhandler) [reply addon-test-support/settings.js]: @rwjblue what about the app (dummay) config also having the ability to set the rootElement? for some reason that was important when we originally defined the rootElement usage with the `find` helper.

**Comment by simonihmig** [comment]
> Having an empty find() return the root element seems ok.

Created another PR for this: #122

File: tests/test-helper.js (hunk 2 above)
Comment (simonihmig) [reply tests/test-helper.js]: Yeah, I noticed how this was working before, but afaict the changes here only affect the internal tests in this addon. The root element should still be configurable I think, as `tests/test-helper.js` does not affect the consumer of this addon, it's just internal, right?

And if we override the setting in the dummy config, we cannot really make sure in our tests that the default setting is what we actually expect. E.g. one could change something in `settings.js` that breaks the behavior, but the tests would not detect this.

File: addon-test-support/settings.js (hunk 1 above)
Comment (simonihmig) [reply addon-test-support/settings.js]: I was using this ability [here](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/test-helper.js#L16) to "fix" the rootElement for my case, and I think we can still keep this feature, but just take the default from the `ember-test-helpers` export when that lands!

**Comment by simonihmig** [comment]
@pixelhandler was I able to address your concerns? If there is anything left I can do to get this to land, happy to do so!

**Comment by simonihmig** [comment]
Rebased to fix conflicts...

@pixelhandler @cibernox sorry to bug you on this again, but is there anything left preventing this from getting merged?

File: tests/test-helper.js (hunk 2 above)
Comment (pixelhandler) [reply tests/test-helper.js]: @simonihmig This code was here as an example of how to deal with setting a custom root element, preferring the config value over something hardcoded in this addon. If the is now another way to do that now then this example can be removed.

File: addon-test-support/settings.js (hunk 1 above)
Comment (pixelhandler) [reply addon-test-support/settings.js]: @rwjblue @simonihmig what about importing the root element from config?

```
import config from '../config/environment'; // does this work? no cause it looks in addon?
const { APP: { rootElement } } = config;

class TestSupportSettings {
  constructor(init = { rootElement }) {

  }
}
```

Comment (simonihmig) [reply addon-test-support/settings.js]: I think your comment is right, it won't work unless the module is in the `app` tree. You would have to dynamically look up the config from DI, afaik. Also `rootElement` in `environment.js` is just `'#ember-testing'` (for test env), while there will still be that wrapping `.ember-view`.

File: tests/test-helper.js (hunk 2 above)
Comment (simonihmig) [reply tests/test-helper.js]: > If the is now another way to do that now then this example can be removed.

No, there is no other way. It works just the same as before, this PR does not touch this!

The example in the Readme is still valid: https://github.com/cibernox/ember-native-dom-helpers#standard-dom-elements-returned-using-a-findfindall-helpers

As I said in the comment above, I removed this from `tests/test-helper.js` because it affects the addon's tests (and only those!). If this was left in place, it would obfuscate the default setting for the test I added [here](https://github.com/cibernox/ember-native-dom-helpers/pull/121/files#diff-c44eb6de9b796fe0f3758d69c2214971). The default setting could be broken, but the addon's tests would still all be passing, because the selector would be overridden in `tests/test-helper.js`. That's why I removed it, to really test with the default selector that any consuming app would see.

I just tested this PR with ember-bootstrap (where I had this issue): 
* overriding the rootElement [here](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/test-helper.js#L16) is not needed anymore (i.e. `:first-child` works correctly with the default setting)
* overriding the rootElement this way still works

**Comment by cibernox** [comment]
I think we can merge this, it's probably a more natural default. I'll release a new version soon-ish.

**Comment by BillyRayPreachersSon** [comment]
Since switching to `ember-power-select: 1.10.4` and `ember-power-select-with-create: 0.5.0`, I seem to have a problem that looks to be related to this issue.

With no other code changes other than revving those two packages, `selectChoose` no longer works for me.

Debugging it down to the `findAll` level shows why: the active dropdown element is inside `#ember-testing`, not inside `#ember-testing > .ember-view`, and since commit [`6300642`](https://github.com/cibernox/ember-native-dom-helpers/commit/6300642eb033c12631fe83b6b22c70594f6dff4c), the default root element has changed to be inside `#ember-testing > .ember-view`.

When the dropdown is opened, I see everything as it should be (all the options show up), and the rendered HTML has this structure:

```
<div id="ember-testing" class="ember-application">
    <div id="ember550" class="ember-view">
        <div class="container">
            <!-- page content here -->
        </div>
    </div>

    <div id="ember-basic-dropdown-content-ember621" class="ember-basic-dropdown-content ember-power-select-dropdown ember-power-select-dropdown--active  ember-basic-dropdown-content--left ember-basic-dropdown-content--below  ember-view">
        <!-- dropdown content here -->
    </div>
</div>
```

As far as I can tell, I'm not using anything out-of-the-ordinary with my markup (I have the usual `{{content-for "body-footer"}}` in my `index.html` file). I've even tried the troubleshooting steps of inserting 
`<div id="ember-basic-dropdown-wormhole"></div>` into my `div.container`, but the active dropdown `<div>` still gets put outside `#ember-testing > .ember-view`, and `findAll` still refuses to find it.

After revving from `ember-power-select: 1.0.0-beta.13` and `ember-power-select-with-create: 0.4.5` to `ember-power-select: 1.10.4` and `ember-power-select-with-create: 0.5.0`, is there anything else I should do to get this test helper to work?

Thanks!

**Comment by BillyRayPreachersSon** [comment]
**Update**: Even if I downgrade back to `ember-power-select: 1.0.0-beta.13` and `ember-power-select-with-create: 0.4.5`, the issue still exists.

I've found that I can update `ember-power-select` to `1.10.4` as long as I downgrade `ember-power-select-with-create` to `0.4.0`. Once I do this, everything starts working fine again. If I update `ember-power-select-with-create` to `0.4.1`, the issue comes back.

That gives me a fix for the time being, at least, but it would be nice to be able to update `ember-power-select-with-create` at some point.

**Comment by simonihmig** [comment]
Seems this is also hardcoded here: https://github.com/cibernox/ember-basic-dropdown/blob/378052af2e544c56074f1da6c6dbe5ccc2de7e8a/addon/components/basic-dropdown.js#L252-L254

**Comment by cibernox** [comment]
I see. I think I've found a way to fix it. We can't make the component render on an element without ID, like `#ember-testing > .ember-view`, but we can use https://github.com/yapplabs/ember-wormhole#what-if-if-my-element-has-no-id and pass `destinationElement` instead of ID.

That way we can put the content of the html inside the "queriable" area of the dom. However, @simonihmig, is `#ember-testing > .ember-view` the root element of the component being tested in integration test? Or the component's root is nested within it? I ask because I think that conceptually, the content of the select should be rendered outside of the element being tested to more accurately mimic how it would render in the real app.

**Comment by simonihmig** [comment]
> is #ember-testing > .ember-view the root element of the component being tested in integration test? Or the component's root is nested within it

The component element is the child of the `.ember-view`. So when rendering this: 
```js
this.render(hbs`{{#my-component class="foo"}}bar{{/my-component}}`);
```

The resulting DOM will look something like this:
```html
<div id="#ember-testing'>
  <div id="ember123" class="ember-view">
    <div id="ember124" class="foo">
      bar
    </div>
  </div>
</div>
```

Does that answer your question?

FWIW, in ember-bootstrap I handle the wormhole a bit differently. The `to` is hardcoded [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/common/bs-modal.hbs#L2), but the `renderInPlace` checks if that container element is present. If not (i.e. in integrations tests, unless you manually add it to your `this.render` template), `renderInPlace` will be true, so rendering this "unwormholed": https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-modal.js#L246. 

When I want to specifically test that the content is wormholed, than I add that container element (here `ember-bootstrap-wormhole`) to the test template: https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-modal-simple-test.js#L492-L501

Does that make sense? Or is even helpful? ¯\\_(ツ)_/¯
